/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biz.readmylegal.backend;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import com.google.common.base.Charsets;
import java.io.IOException;
import java.util.Scanner;

public class App {
    private int port;
    private String password;
    private HttpBackend http;
    private File tokenFile;

    public App(int port, String password, File tokenFile) throws IOException {
        this.port = port;
        this.password = password;
        this.tokenFile = tokenFile;
    }

    public int getPort() {
        return this.port;
    }

    public void start() throws IOException {
        http = new HttpBackend(port, password, tokenFile);
        http.start();
    }

    public void stop() {
        http.stop();
    }

    public static void main(String[] args) throws Exception {
        // Args: port password tokenpath
        App app = new App(Integer.parseInt(args[0]), args[1], new File(args[2]));
        app.start();
        System.out.println("Listening on 127.0.0.1:" + app.getPort());
        System.out.println("Type `exit` to close the server.");
        awaitExit();
        System.out.println("Closing server, please wait...");
        app.stop();
        System.out.println("Have a nice day!");

        //Speech to text 
       //RequestHttp.test2();
        //Text to Speech
       // TextToSpeech.textToSpeech();
    }

    private static void awaitExit() {
        Scanner scanner = new Scanner(System.in);
        while (!scanner.nextLine().equals("exit"));
        scanner.close();
    }

}
