/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biz.readmylegal.backend;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import com.google.common.base.Charsets;

public class App {
    private String test;

    public App() {
        test = "Hello world!";
    }

    public void print() {
        System.out.println(test);
    }

    public static void main(String[] args) throws IOException {
        HttpTest.test1();
        //GPTTest.test(tokenContents());
    }

    // Returns the contents of a token file in the home directory
    // Do not use this in production
    private static String tokenContents() {
        String path = System.getProperty("user.home") + "/openai-token.txt";
        File file = new File(path);
        if (!file.isFile())
            return "";
        
        FileInputStream inFile;

        try {
            inFile = new FileInputStream(file);
        } catch (FileNotFoundException e) {
            return "";
        }

        String token;

        try {
            token = new String(inFile.readAllBytes(), Charsets.UTF_8).strip();
        } catch (IOException e) {
            try {
                inFile.close();
            } catch (IOException e1) {
                return "";
            }
            return "";
        }

        try {
            inFile.close();
        } catch (IOException e) {
            return "";
        }

        return token;
    }
}
