/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biz.readmylegal.backend;

import org.junit.jupiter.api.Test;

import java.io.IOException;

class AppTest {
    @Test void appExists() throws IOException {
        @SuppressWarnings("unused")
        App app = new App(12345);
    }
}
